### ISSUE TITLE
Not a gzipped file (b'<!')

### ISSUE THREAD

**Issue by AngDH** [CLannadZSY/scrapy-middlewares#1]
`
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pyenv\scrapy\lib\site-packages\twisted\internet\defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "D:\pyenv\scrapy\lib\site-packages\scrapy\core\downloader\middleware.py", line 55, in process_response
    response = yield deferred_from_coro(method(request=request, response=response, spider=spider))
  File "D:\pyenv\scrapy\lib\site-packages\scrapy\downloadermiddlewares\httpcompression.py", line 46, in process_response
    decoded_body = self._decode(response.body, encoding.lower())
  File "D:\pyenv\scrapy\lib\site-packages\scrapy\downloadermiddlewares\httpcompression.py", line 63, in _decode
    body = gunzip(body)
  File "D:\pyenv\scrapy\lib\site-packages\scrapy\utils\gz.py", line 28, in gunzip
    chunk = f.read1(8196)
  File "c:\program files\python37\lib\gzip.py", line 300, in read1
    return self._buffer.read1(size)
  File "c:\program files\python37\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "c:\program files\python37\lib\gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "c:\program files\python37\lib\gzip.py", line 422, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<!')

`

**Comment by CLannadZSY** [comment]
贴上你使用这个中间件的完整代码
